# tesing.yml

- name: Setup servers on Amazon EC2 machines
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - include_vars: group_vars/all/ec2_vars.yml

    - name: Amazon EC2 | Create Key Pair
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        key_material: "{{ item }}"
        force: false
      with_file: ~/.ssh/id_rsa.pub

    - name: Amazon EC2 | Provision Instance
      ec2:
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        zone: "{{ zone }}"
        group: "{{ group }}"
        instance_type: "{{ machine }}"
        image: "{{ image }}"
        wait: true
        vpc_subnet_id: "{{ subnet_id }}"
        assign_public_ip: yes
        exact_count: "{{ exact_count }}" # makes it idempotent
        count_tag:
            Name: Demo
        instance_tags:
            Name: Demo
      register: ec2

    - name: Amazon EC2 | Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Amazon EC2 | Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ ec2.instances }}"

- name: Configure instance
  hosts: launched
  become: True
  connection: ssh
  remote_user: ubuntu
  gather_facts: True
  roles:
    - cloudalchemy.prometheus
    - gantsign.golang
