# tesing.yml

- name: Setup servers on Amazon EC2 machines
  hosts: localhost
  gather_facts:

  tasks:
    - include_vars: group_vars/all/ec2_vars.yml

    - name: Amazon EC2 | Create Key Pair
      ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
        key_material: "{{ item }}"
      with_file: ~/.ssh/id_rsa.pub

    - name: Amazon EC2 | Provision Instance
      ec2:
        key_name: "{{ key_name }}"
        count: "{{ count }}"
        region: "{{ region }}"
        zone: "{{ zone }}"
        group: "{{ group }}"
        instance_type: "{{ machine }}"
        image: "{{ image }}"
        wait: true
        wait_timeout: 500
        # assign_public_ip: yes
      register: ec2

    # - name: Amazon EC2 | Wait for SSH to come up
    #   wait_for:
    #     host: "{{ item.public_ip }}"
    #     port: 22
    #     delay: 10
    #     timeout: 60
    #     state: started
    #   with_items: "{{ ec2.instances }}"
