- name: Restart the alertmanager service
  service:
    name: alertmanager
    state: restarted
  listen: event_restart_alertmanager

- name: Reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload